/**
 * Pure decisions for the Electron main process (no electron import, so they are unit-tested in plain node).
 *
 * The per-launch admin secret is generated by main, written to its own core child's stdin and kept in memory. Main only gives it to the
 * renderer when it has just seen THAT child answer /health with `admin: true` and its own pid, so a foreign core (started by the MCP
 * bridge, a terminal, or anything else on the port) never receives it.
 */

export interface CoreHealth { ok?: boolean; version?: string; pid?: number; admin?: boolean }

/** The secret to hand to the renderer, or undefined. Only when the core on the port is the child we spawned and it holds a secret. */
export function adminForRenderer(health: CoreHealth | null | undefined, corePid: number | undefined, secret: string | undefined): string | undefined {
  if (!secret || !health || !corePid) return undefined;
  if (health.pid !== corePid || health.admin !== true) return undefined;
  return secret;
}

/** Whether a /health `pid` can be stopped: a positive integer that is not this process. A liar on the port must not make main kill itself. */
export function stoppablePid(pid: unknown, selfPid: number): pid is number {
  return typeof pid === 'number' && Number.isInteger(pid) && pid > 1 && pid !== selfPid;
}

/** True when a core's state snapshot shows work that a restart would cut off. Anything unreadable counts as busy (fail safe). */
export function coreIsBusy(state: unknown): boolean {
  if (!state || typeof state !== 'object') return true;
  const s = state as { tasks?: unknown; approvals?: unknown };
  if (!Array.isArray(s.tasks) || !Array.isArray(s.approvals)) return true;
  if (s.approvals.length > 0) return true;
  return s.tasks.some((t) => !!t && typeof t === 'object' && ['queued', 'running'].includes((t as { status?: string }).status ?? ''));
}

export type CoreAction =
  /** Nothing answers on the port: spawn our own core. */
  | 'spawn'
  /** The core on the port is our child and holds the admin secret. */
  | 'use'
  /** A foreign or secret-less core, idle: stop it by pid and spawn our own. */
  | 'replace'
  /** A foreign or secret-less core with running tasks or pending approvals: ask the person (restart now / later). */
  | 'ask'
  /** A foreign core whose pid cannot be used: tell the person to stop it themselves. */
  | 'blocked';

export function coreAction(i: { health: CoreHealth | null | undefined; ourPid: number | undefined; busy: boolean; selfPid: number }): CoreAction {
  if (!i.health) return 'spawn';
  if (i.ourPid !== undefined && i.health.pid === i.ourPid && i.health.admin === true) return 'use';
  if (!stoppablePid(i.health.pid, i.selfPid)) return 'blocked';
  return i.busy ? 'ask' : 'replace';
}
