/**
 * Pure decisions for the Electron main process (no electron import, so they are unit-tested in plain node).
 *
 * The per-launch admin secret is generated by main, written to its own core child's stdin and kept in memory. Main only gives it to the
 * renderer when the core on the port has just answered a fresh challenge: `GET /health?nonce=<random>` must return
 * HMAC-SHA256(secret, nonce). That proves the answering server holds the secret, whatever its pid (a `node` shim spawns a different pid),
 * and nothing that merely copies our child's public pid can pass it.
 */
import { healthProof, isHexNonce } from '../core/admin.js';
import { timingSafeEqual } from 'node:crypto';

export interface CoreHealth { ok?: boolean; version?: string; pid?: number; admin?: boolean; proof?: string }

/** True when `health.proof` is the right HMAC of `nonce` under `secret`. */
export function proofValid(health: CoreHealth | null | undefined, secret: string | undefined, nonce: string): boolean {
  if (!secret || !health || health.admin !== true || typeof health.proof !== 'string' || !isHexNonce(nonce)) return false;
  const want = Buffer.from(healthProof(secret, nonce));
  const got = Buffer.from(health.proof);
  return want.length === got.length && timingSafeEqual(want, got);
}

/** The secret to hand to the renderer, or undefined. Only when the core on the port proved it holds the secret. */
export function adminForRenderer(health: CoreHealth | null | undefined, secret: string | undefined, nonce: string): string | undefined {
  return proofValid(health, secret, nonce) ? secret : undefined;
}

/** Whether a /health `pid` can be stopped: a positive integer that is not this process. A liar on the port must not make main kill itself. */
export function stoppablePid(pid: unknown, selfPid: number): pid is number {
  return typeof pid === 'number' && Number.isInteger(pid) && pid > 1 && pid !== selfPid;
}

/** True when a core's state snapshot shows work that a restart would cut off. Anything unreadable counts as busy (fail safe). */
export function coreIsBusy(state: unknown): boolean {
  if (!state || typeof state !== 'object') return true;
  const s = state as { tasks?: unknown; approvals?: unknown };
  if (!Array.isArray(s.tasks) || !Array.isArray(s.approvals)) return true;
  if (s.approvals.length > 0) return true;
  return s.tasks.some((t) => !!t && typeof t === 'object' && ['queued', 'running'].includes((t as { status?: string }).status ?? ''));
}

export type CoreAction =
  /** Nothing answers on the port: spawn our own core. */
  | 'spawn'
  /** The core on the port proved it holds our admin secret. */
  | 'use'
  /** A foreign or secret-less core, idle: stop it by pid and spawn our own. */
  | 'replace'
  /** A foreign or secret-less core with running tasks or pending approvals: ask the person (restart now / later). */
  | 'ask'
  /** A foreign core whose pid cannot be used: tell the person to stop it themselves. */
  | 'blocked';

/** `ownProof` = the core answered our challenge correctly (see proofValid). */
export function coreAction(i: { health: CoreHealth | null | undefined; ownProof: boolean; busy: boolean; selfPid: number }): CoreAction {
  if (!i.health) return 'spawn';
  if (i.ownProof) return 'use';
  if (!stoppablePid(i.health.pid, i.selfPid)) return 'blocked';
  return i.busy ? 'ask' : 'replace';
}
