#!/usr/bin/env node
/**
 * Copies the pure desktop files the Claude Code mod reuses into mod/vendor/legion/, so the mod runs the same logic as the app.
 *
 * One transform only: relative import specifiers ending in `.js` become `.ts` (the mod loader and Node's type stripping read the
 * `.ts` files directly; the desktop compiles with NodeNext, which spells them `.js`). Every other byte is the source's.
 * test/mod-vendor.test.ts fails when a vendored file drifts from its source. Run `node scripts/build-mod.mjs` after changing any
 * file listed here, and commit the result: a marketplace install from git does not run this script.
 *
 * Only files with no runtime import of node:* belong here (type-only imports are fine). Files that need crypto or fs get a
 * mod-side adapter instead (mod/src/...), never a vendored copy.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'mod', 'vendor', 'legion');

/** Repo-relative paths, kept as the same relative paths under mod/vendor/legion/. */
export const VENDORED = [
  'src/shared/types.ts',
  'src/shared/comms.ts',
  'src/shared/blender.ts',
  'src/shared/projects.ts',
  'src/shared/kg.ts',
  'src/shared/board.ts',
  'src/core/router.ts',
  'src/core/model-cap.ts',
  'src/core/roster.ts',
  'src/core/kg/types.ts',
  'src/core/kg/text.ts',
  'src/core/kg/briefing.ts',
  'src/core/kg/capture.ts',
  'src/core/kg/quota.ts',
];

/** The one transform: `from './x.js'` -> `from './x.ts'` for relative specifiers. Exported for the parity test. */
export const toModSource = (text) => text.replace(/(\bfrom\s+['"])(\.{1,2}\/[^'"]+)\.js(['"])/g, '$1$2.ts$3');

function main() {
  rmSync(OUT, { recursive: true, force: true });
  for (const rel of VENDORED) {
    const src = readFileSync(join(ROOT, rel), 'utf8');
    if (/\bfrom\s+['"]node:/.test(src.replace(/import\s+type[^;]+;/g, ''))) throw new Error(`${rel} imports node:* at runtime: it cannot be vendored`);
    const dest = join(OUT, rel);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, toModSource(src));
  }
  writeFileSync(join(OUT, 'manifest.json'), JSON.stringify({ note: 'Generated by scripts/build-mod.mjs. Do not edit these files; edit the source and re-run.', files: VENDORED }, null, 2) + '\n');
  console.log(`vendored ${VENDORED.length} files into mod/vendor/legion/`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
